title: Sorveteria Itapolitana Cajuru
description: Sorvete artesanal em Cajuru SP
baseurl: 
url: https://itapolitanacajuru.com.br
markdown: kramdown
theme: jekyll-theme-primer
exclude: [assets/css, assets/js, dados, node_modules]